# Generated by Django 3.2.7 on 2021-09-06 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0002_rename_jenis_kelamin_pelatih_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelatih',
            name='Tanggal_Input',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
