# Generated by Django 3.2.7 on 2021-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0003_alter_pelatih_tanggal_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelatih',
            name='Status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('tidak aktif', 'Tidak Aktif')], max_length=15),
        ),
    ]
