# Generated by Django 3.2.7 on 2021-09-10 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taekwondo', '0004_alter_pelatih_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelatih',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='pelatih',
            name='Manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
