# Generated by Django 5.1.4 on 2024-12-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0007_alter_coach_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
