# Generated by Django 5.1.4 on 2025-01-03 20:46

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0008_alter_coach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
