# Generated by Django 5.1.4 on 2025-01-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0009_coach_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
