# Generated by Django 5.1.4 on 2025-01-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0010_coach_achievements_coach_bio_coach_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='experience_years',
        ),
    ]
